# Generated by Django 2.0.1 on 2018-02-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_list_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_info',
            name='Tel',
            field=models.CharField(max_length=11),
        ),
    ]
