# Generated by Django 2.0.1 on 2018-02-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180205_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_info',
            name='user_sex',
            field=models.CharField(choices=[('man', 'male'), ('woman', 'female')], default='', max_length=5),
        ),
    ]
