# Generated by Django 2.0.1 on 2018-02-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_list_info_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_info',
            name='img',
            field=models.ImageField(default='', upload_to='img/%Y/%m', verbose_name='Narrow of img'),
        ),
    ]
